"use client";

import { useQueryClient } from "@tanstack/react-query";
import { ImagePlus, UploadCloud } from "lucide-react";
import { useRef, useState } from "react";
import { api } from "@/lib/api";
import type { DetectionEvent } from "@/lib/types";
import { formatConfidence } from "@/lib/utils";
import { Badge, Button, Card, EmptyState, PageTitle } from "@/components/ui";

export default function DetectPage() {
  const input = useRef<HTMLInputElement>(null); const queryClient = useQueryClient();
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState(""); const [result, setResult] = useState<DetectionEvent | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  function choose(next?: File) { setError(""); setResult(null); if (!next) return; if (!["image/jpeg", "image/png", "image/webp"].includes(next.type)) return setError("Gunakan gambar JPG, PNG, atau WEBP."); if (next.size > 10 * 1024 * 1024) return setError("Ukuran gambar maksimal 10 MB."); setFile(next); setPreview(URL.createObjectURL(next)); }
  async function detect() { if (!file) return; setLoading(true); setError(""); const form = new FormData(); form.append("file", file); try { const response = await api<DetectionEvent>("/api/detections/images", { method: "POST", body: form }); setResult(response.data); queryClient.invalidateQueries({ queryKey: ["dashboard"] }); } catch (err) { setError(err instanceof Error ? err.message : "Deteksi gagal."); } finally { setLoading(false); } }
  return <><PageTitle title="Deteksi gambar" description="Unggah foto mata entok untuk menjalankan inferensi YOLO."/><div className="grid gap-6 lg:grid-cols-2"><Card><button type="button" onClick={() => input.current?.click()} onDragOver={(e) => e.preventDefault()} onDrop={(e) => { e.preventDefault(); choose(e.dataTransfer.files[0]); }} className="grid min-h-72 w-full place-items-center overflow-hidden rounded-2xl border-2 border-dashed border-slate-300 bg-slate-50 transition hover:border-emerald-500 dark:border-slate-700 dark:bg-slate-950">{preview ? <img src={preview} alt="Preview upload" className="max-h-96 w-full object-contain"/> : <div className="text-center"><UploadCloud className="mx-auto mb-3 text-emerald-600" size={40}/><p className="font-semibold">Klik atau letakkan gambar di sini</p><p className="mt-1 text-sm text-slate-500">JPG, PNG, WEBP · maksimal 10 MB</p></div>}</button><input ref={input} type="file" accept="image/jpeg,image/png,image/webp" className="hidden" onChange={(e) => choose(e.target.files?.[0])}/>{file && <div className="mt-4 flex items-center justify-between gap-4"><div className="min-w-0"><p className="truncate text-sm font-medium">{file.name}</p><p className="text-xs text-slate-500">{(file.size / 1024).toFixed(0)} KB</p></div><Button onClick={detect} disabled={loading}>{loading ? "Mendeteksi..." : "Jalankan deteksi"}</Button></div>}{error && <p className="mt-4 rounded-xl bg-rose-50 p-3 text-sm text-rose-700 dark:bg-rose-950/40">{error}</p>}</Card><Card>{result ? <div><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Hasil deteksi</h2><Badge tone={result.outcome === "abnormal" ? "red" : result.outcome === "normal" ? "green" : "yellow"}>{result.outcome}</Badge></div>{result.annotated_url ? <img src={result.annotated_url} alt="Hasil anotasi" className="max-h-96 w-full rounded-2xl bg-slate-950 object-contain"/> : null}<div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><p className="text-slate-500">Confidence</p><p className="font-bold">{formatConfidence(result.max_confidence)}</p></div><div className="rounded-xl bg-slate-100 p-3 dark:bg-slate-800"><p className="text-slate-500">Objek</p><p className="font-bold">{result.detection_count}</p></div></div><div className="mt-4 space-y-2">{result.detections?.map((item) => <div key={item.id} className="flex items-center justify-between rounded-xl border p-3 text-sm"><span className="capitalize">{item.label}</span><span>{formatConfidence(item.confidence)}</span></div>)}</div></div> : <EmptyState title="Hasil belum tersedia" description="Pilih gambar dan jalankan deteksi untuk melihat anotasi."/>}</Card></div></>;
}
