"use client";

import { useQuery } from "@tanstack/react-query";
import { Activity, CameraOff, Radio } from "lucide-react";
import { api } from "@/lib/api";
import { formatConfidence, formatDate } from "@/lib/utils";
import { Badge, Card, EmptyState, PageTitle } from "@/components/ui";

type CameraStatus = { status: string; error: string | null; fps: number; camera_id: number | null; has_frame: boolean; last_detection: null | { event_id: number; outcome: string; confidence: number | null; detected_at: string } };

export default function MonitoringPage() {
  const { data } = useQuery({ queryKey: ["camera-status"], queryFn: () => api<CameraStatus>("/api/camera/status"), refetchInterval: 2000 });
  const status = data?.data;
  return <><PageTitle title="Live monitoring" description="Pantau satu sumber kamera aktif dan hasil inferensi terakhir." action={<Badge tone={status?.status === "running" ? "green" : status?.status === "error" ? "red" : "slate"}>{status?.status ?? "memuat"}</Badge>}/><div className="grid gap-6 xl:grid-cols-[1.5fr_1fr]"><Card className="overflow-hidden p-0"><div className="flex aspect-video items-center justify-center bg-slate-950">{status?.has_frame && status.status === "running" ? <img src="/api/camera/stream.mjpg" alt="Live kamera entok" className="h-full w-full object-contain"/> : <div className="text-center text-slate-400"><CameraOff className="mx-auto mb-3" size={44}/><p>{status?.error ?? "Kamera belum dijalankan oleh admin."}</p></div>}</div><div className="flex items-center justify-between p-4"><div className="flex items-center gap-2 text-sm"><span className={status?.status === "running" ? "size-2 rounded-full bg-emerald-500 animate-pulse" : "size-2 rounded-full bg-slate-400"}/><span className="capitalize">{status?.status ?? "stopped"}</span></div><span className="text-sm text-slate-500">{status?.fps ?? 0} FPS</span></div></Card><div className="space-y-6"><Card><div className="mb-4 flex items-center gap-3"><div className="grid size-10 place-items-center rounded-xl bg-emerald-100 text-emerald-700"><Radio size={20}/></div><div><h2 className="font-bold">Deteksi terakhir</h2><p className="text-xs text-slate-500">Diperbarui otomatis</p></div></div>{status?.last_detection ? <div className="space-y-3"><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Hasil</span><Badge tone={status.last_detection.outcome === "abnormal" ? "red" : "green"}>{status.last_detection.outcome}</Badge></div><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Confidence</span><span className="font-semibold">{formatConfidence(status.last_detection.confidence)}</span></div><div className="flex items-center justify-between"><span className="text-sm text-slate-500">Waktu</span><span className="text-sm">{formatDate(status.last_detection.detected_at)}</span></div></div> : <EmptyState title="Belum ada hasil" description="Deteksi akan tampil ketika kamera aktif."/>}</Card><Card><div className="flex items-start gap-3"><Activity className="mt-0.5 text-amber-500"/><div><h2 className="font-bold">Catatan keselamatan</h2><p className="mt-2 text-sm leading-6 text-slate-500">Hasil AI adalah penyaringan awal. Pastikan pencahayaan dan fokus kamera baik, lalu konsultasikan hasil abnormal kepada tenaga veteriner.</p></div></div></Card></div></div></>;
}
