"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { api } from "@/lib/api";
import type { User } from "@/lib/types";
import { formatDate } from "@/lib/utils";
import { Badge, Button, Card, Input, PageTitle, Select } from "@/components/ui";

export default function UsersPage() {
  const client = useQueryClient(); const [form, setForm] = useState({ username: "", full_name: "", password: "", role: "operator" });
  const { data, isLoading } = useQuery({ queryKey: ["users"], queryFn: () => api<User[]>("/api/users") });
  const create = useMutation({ mutationFn: () => api("/api/users", { method: "POST", body: JSON.stringify(form) }), onSuccess: () => { setForm({ username: "", full_name: "", password: "", role: "operator" }); client.invalidateQueries({ queryKey: ["users"] }); } });
  async function toggle(user: User) { await api(`/api/users/${user.id}`, { method: "PATCH", body: JSON.stringify({ is_active: !user.is_active }) }); client.invalidateQueries({ queryKey: ["users"] }); }
  async function reset(user: User) { const password = window.prompt(`Password baru untuk ${user.username} (minimal 8 karakter)`); if (!password) return; await api(`/api/users/${user.id}/reset-password`, { method: "POST", body: JSON.stringify({ password }) }); window.alert("Password berhasil direset."); }
  return <><PageTitle title="Manajemen pengguna" description="Kelola akun admin dan operator."/><div className="grid gap-6 xl:grid-cols-[360px_1fr]"><Card><h2 className="font-bold">Tambah pengguna</h2><div className="mt-4 space-y-3"><Input placeholder="Username" value={form.username} onChange={(e) => setForm({ ...form, username: e.target.value })}/><Input placeholder="Nama lengkap" value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })}/><Input type="password" placeholder="Password minimal 8 karakter" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })}/><Select className="w-full" value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })}><option value="operator">Operator</option><option value="admin">Admin</option></Select><Button className="w-full" onClick={() => create.mutate()} disabled={create.isPending}>{create.isPending ? "Menyimpan..." : "Buat akun"}</Button>{create.error && <p className="text-sm text-rose-600">{create.error.message}</p>}</div></Card><Card className="overflow-x-auto p-0"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b bg-slate-50 text-xs uppercase text-slate-500 dark:border-slate-800 dark:bg-slate-950"><tr><th className="px-5 py-4">Pengguna</th><th className="px-5 py-4">Role</th><th className="px-5 py-4">Status</th><th className="px-5 py-4">Login terakhir</th><th className="px-5 py-4"/></tr></thead><tbody>{data?.data.map((user) => <tr key={user.id} className="border-b last:border-0 dark:border-slate-800"><td className="px-5 py-4"><p className="font-semibold">{user.full_name}</p><p className="text-xs text-slate-500">@{user.username}</p></td><td className="px-5 py-4 capitalize">{user.role}</td><td className="px-5 py-4"><Badge tone={user.is_active ? "green" : "red"}>{user.is_active ? "Aktif" : "Nonaktif"}</Badge></td><td className="px-5 py-4">{formatDate(user.last_login_at)}</td><td className="px-5 py-4"><div className="flex justify-end gap-2"><Button variant="secondary" size="sm" onClick={() => reset(user)}>Reset</Button><Button variant={user.is_active ? "danger" : "secondary"} size="sm" onClick={() => toggle(user)}>{user.is_active ? "Nonaktifkan" : "Aktifkan"}</Button></div></td></tr>)}</tbody></table>{isLoading && <p className="p-8 text-center text-slate-500">Memuat pengguna...</p>}</Card></div></>;
}
