import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva("inline-flex items-center justify-center gap-2 rounded-xl text-sm font-semibold transition disabled:pointer-events-none disabled:opacity-50 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500", { variants: { variant: { primary: "bg-emerald-600 text-white shadow-sm hover:bg-emerald-700", secondary: "border border-slate-200 bg-white text-slate-700 hover:bg-slate-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-100", danger: "bg-rose-600 text-white hover:bg-rose-700", ghost: "text-slate-600 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-800" }, size: { sm: "h-9 px-3", md: "h-11 px-4", lg: "h-12 px-6" } }, defaultVariants: { variant: "primary", size: "md" } });

export function Button({ className, variant, size, ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & VariantProps<typeof buttonVariants>) { return <button className={cn(buttonVariants({ variant, size }), className)} {...props} />; }
export function Card({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) { return <div className={cn("rounded-2xl border border-slate-200/80 bg-white p-5 shadow-sm dark:border-slate-800 dark:bg-slate-900", className)} {...props} />; }
export function Input({ className, ...props }: React.InputHTMLAttributes<HTMLInputElement>) { return <input className={cn("h-11 w-full rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none transition placeholder:text-slate-400 focus:border-emerald-500 focus:ring-2 focus:ring-emerald-500/20 dark:border-slate-700 dark:bg-slate-950", className)} {...props} />; }
export function Select({ className, ...props }: React.SelectHTMLAttributes<HTMLSelectElement>) { return <select className={cn("h-11 rounded-xl border border-slate-200 bg-white px-3 text-sm outline-none focus:border-emerald-500 dark:border-slate-700 dark:bg-slate-950", className)} {...props} />; }
export function Badge({ children, tone = "slate" }: { children: React.ReactNode; tone?: "green" | "red" | "yellow" | "slate" }) { const colors = { green: "bg-emerald-100 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300", red: "bg-rose-100 text-rose-700 dark:bg-rose-950 dark:text-rose-300", yellow: "bg-amber-100 text-amber-700 dark:bg-amber-950 dark:text-amber-300", slate: "bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300" }; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-semibold", colors[tone])}>{children}</span>; }
export function PageTitle({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-bold tracking-tight text-slate-950 dark:text-white">{title}</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{description}</p></div>{action}</div>; }
export function EmptyState({ title, description }: { title: string; description: string }) { return <div className="rounded-2xl border border-dashed border-slate-300 px-6 py-12 text-center dark:border-slate-700"><p className="font-semibold">{title}</p><p className="mt-1 text-sm text-slate-500">{description}</p></div>; }
