# Dataset berlabel aktif. Folder dataset/images tidak digunakan untuk training
# karena hanya menjadi tempat penyimpanan awal foto mentah tanpa anotasi.
path: "../dataset/labels/datav1"

train: train/images
val: valid/images
test: test/images

nc: 2
names:
  0: abnormal
  1: normal

allow_empty_labels: true
split_grouping: original_id
