# Eksperimen satu kelas untuk mendeteksi mata normal.
# Model ini tidak dapat menyimpulkan bahwa objek yang tidak terdeteksi pasti abnormal.

model: yolo26m.pt
data: data_normal_only.yaml
expected_names: [normal]

epochs: 150
imgsz: 960
batch: 5
device: 0
workers: 1
patience: 0
name: entok_eye_normal_only_960
